// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEnrollmentWebApp.Data;

#nullable disable

namespace StudentEnrollmentWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240217091903_SeedStudentTable")]
    partial class SeedStudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentEnrollmentWebApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "123 Main St, City",
                            Course = "Engineering",
                            DateModified = new DateTime(2024, 2, 17, 17, 19, 2, 829, DateTimeKind.Local).AddTicks(108),
                            DateOfBirth = new DateOnly(1999, 5, 15),
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            Gender = "Male",
                            PhoneNumber = "123-456-7890",
                            Section = "A",
                            Semester = "1st Semester",
                            Subjects = "Math,English,Science",
                            YearLevel = "2nd Year"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "456 Elm St, Town",
                            Course = "Business",
                            DateModified = new DateTime(2024, 2, 17, 17, 19, 2, 829, DateTimeKind.Local).AddTicks(126),
                            DateOfBirth = new DateOnly(2000, 2, 20),
                            Email = "emily.johnson@example.com",
                            FullName = "Emily Johnson",
                            Gender = "Female",
                            PhoneNumber = "987-654-3210",
                            Section = "B",
                            Semester = "2nd Semester",
                            Subjects = "History,Economics",
                            YearLevel = "1st Year"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "789 Oak St, Village",
                            Course = "Psychology",
                            DateModified = new DateTime(2024, 2, 17, 17, 19, 2, 829, DateTimeKind.Local).AddTicks(173),
                            DateOfBirth = new DateOnly(1998, 11, 10),
                            Email = "michael.brown@example.com",
                            FullName = "Michael Brown",
                            Gender = "Male",
                            PhoneNumber = "555-123-4567",
                            Section = "C",
                            Semester = "1st Semester",
                            Subjects = "Psychology,Sociology",
                            YearLevel = "3rd Year"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
